# Generated by Django 5.2.8 on 2025-12-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_caritem_cart_alter_caritem_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarItem',
            new_name='CartItem',
        ),
    ]
